### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by mohammedbalila** [shazaaly/node-ecommerce#1]
Hello @shazaaly 
I hope you're well, I saw your post on LinkedIn about this project and though to check it out.
You're doing an amazing work wish you all the best, I just have a few observations.

- **Separate the app from the server**, The express app logic should be separated from the server (network) logic for easier testing and maintainability. [why express app and server files kept separately](https://www.geeksforgeeks.org/why-express-app-and-server-files-kept-separately/)
- **Do not validate user input inside your controllers**, use middlewares with something like [express-validator](https://express-validator.github.io/docs/) instead. [express-validator-in-express-js](https://www.digitalocean.com/community/tutorials/how-to-handle-form-inputs-efficiently-with-express-validator-in-express-js)
- **In your server.js file handle clean-up after the server closes**: you can use something like [close-with-grace](https://www.npmjs.com/package/close-with-grace)
```javascript
const mongoose = require('mongoose');
const closeWithGrace = require('close-with-grace');
const { logger } = require('./config/logger');
const app = require('./app');

const port = process.env.PORT;
async function start() {
  try {
    await mongoose.connect(process.env.DB_URI);

    mongoose.connection.on('error', (error) => {
      logger.error(error);
      process.exit(1);
    });

    app
      .listen(port, () => {
        logger.info(`Listing on port ${port}`);
      })
      .on('error', (e) => {
        process.exit(1);
      });
  } catch (error) {
    // close db connection
    logger.error(error);
    mongoose.connection.close();
    process.exit(1);
  }
}

start();

// gracefully shutdown the server and close opened db connections
// grace period is the wait time before closing the server
const gracePeriod = 2 * 1000; // 2s
closeWithGrace(
  { delay: gracePeriod },
  async function ({ signal, err, manual }) {
    if (err) {
      logger.error(err);
    }
    await mongoose.connection.close();
  },
);
```
- **Don't return sensitive information**: such as user passwords/secrets in your api response
- **Keep your config in one place** and reuse it across the application
   - things like email service config
   - Auth tokens related functionality etc...
- **You're using MongoDB which is a NoSQL database**, but you model your data as if you're using a relastional database. Maybe try the document model and see if it works for you, with NoSQL database your schema should always nest unless you have a reason not to [mongodb-relationships-embed-or-reference](https://stackoverflow.com/questions/5373198/mongodb-relationships-embed-or-reference), [mongodb-applied-design](https://www.oreilly.com/library/view/mongodb-applied-design/9781449340056/ch01.html)
#### Hope this helps, and please feel free to correct any point that you think is invalid or wrong

**Comment by shazaaly** [comment]
Hello @mohammedbalila 
I really appreciate your observations and going to investigate and work on every one, and I will appreciate your feedback for my future updates regarding them.
Thank you.

**Comment by mohammedbalila** [comment]
Great, good luck!
Don't hesitate to reach out to me anytime, here or on [linkedin](https://www.linkedin.com/in/mohammedbalila/)
